spring:
  elasticsearch:
    uris: http://localhost:9200
    connection-timeout: 1s
    socket-timeout: 3s
#    추후 xpack.security.enabled=false 변경 시
#    username: elastic
#    password: your_password
# 테스트용
