spring:
  datasource:
    url: ${PRODUCT_DATABASE_URL}
    driver-class-name: org.postgresql.Driver
    username: ${PRODUCT_DATABASE_USERNAME}
    password: ${PRODUCT_DATABASE_PASSWORD}
  jackson:
    time-zone: Asia/Seoul
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: Asia/Seoul
  batch:
    jdbc:
      table-prefix: batch_product_schema.batch_
      initialize-schema: never
