#file: noinspection KubernetesUnknownValues
apiVersion: apps/v1
kind: Deployment
metadata:
  name: member
spec:
  replicas: 1
  selector:
    matchLabels:
      app: member
  template:
    metadata:
      labels:
        app: member
    spec:
      automountServiceAccountToken: false
      containers:
        - name: member
          image: minbros/member
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: member-secret
          env:
            - name: SPRING_CLOUD_CONFIG_URI
              value: "http://config-service:8888"
            - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
              value: "http://admin:admin@discovery-service:8761/eureka"
            - name: EUREKA_INSTANCE_HOSTNAME
              value: "discovery-service"
            - name: GATEWAY_HOST
              value: "http://gateway-service:8000"
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "http://kafka-service:9092"
          resources:
            requests:
              cpu: "200m"
              memory: "384Mi"
              ephemeral-storage: "512Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
              ephemeral-storage: "1Gi"
          ports:
            - containerPort: 8083
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8083
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8083
            initialDelaySeconds: 60
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: member-service
spec:
  selector:
    app: member
  ports:
    - port: 8083
      targetPort: 8083
  type: ClusterIP
