#file: noinspection SpellCheckingInspection, HttpUrlsUsage
spring:
  application:
    name: member

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/group_purchase?currentSchema=notification_schema}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none #validate
    properties:
      hibernate:
        format_sql: true
        show-sql: false
    open-in-view: false

  flyway:
    enabled: true
    default-schema: member_schema
    schemas:
      - member_schema
      - notification_schema
    create-schemas: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MEMBER_SMTP_EMAIL}
    password: ${MEMBER_SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8083

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

  otlp:
    metrics:
      export:
        enabled: false

kafka:
  bootstrap-servers: ${spring.kafka.bootstrap-servers}

jwt:
  secret: ${JWT_SECRET}
  access-token-validity-period: ${JWT_ACCESS_TOKEN_VALIDITY_PERIOD}
  refresh-token-validity-period: ${JWT_REFRESH_TOKEN_VALIDITY_PERIOD}

springdoc:
  swagger-ui:
    disable-swagger-default-url: true
  default-flat-param-object: true

resilience4j:
  retry:
    instances:
      pointClient:
        max-attempts: 2
        wait-duration: 500ms
      CommerceClient:
        max-attempts: 2
        wait-duration: 500ms
