#file: noinspection SpellCheckingInspection
spring:
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

commerce-service:
  url: ${COMMERCE_SERVICE_URL}

point-service:
  url: ${POINT_SERVICE_URL}

cookie:
  same-site: None
  secure: true
