#file: noinspection SpellCheckingInspection
spring:
  data:
    redis:
      host: localhost
      port: 6379

  r2dbc:
    url: ${SPRING_R2DBC_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: member-api
              uri: http://localhost:8083
              predicates:
                - Path=/api/members/**, /api/auth/**, /api/notifications/**

            - id: member-api-docs
              uri: http://localhost:8083
              predicates:
                - Path=/v3/api-docs/member
              filters:
                - RewritePath=/v3/api-docs/member, /v3/api-docs

            - id: commerce-api
              uri: http://localhost:8087
              predicates:
                - Path=/api/orders/**, /api/carts/**, /api/balances/**, /api/products/**, /api/purchases/**

            - id: commerce-api-docs
              uri: http://localhost:8087
              predicates:
                - Path=/v3/api-docs/commerce
              filters:
                - RewritePath=/v3/api-docs/commerce, /v3/api-docs

            - id: point-api
              uri: http://localhost:8086
              predicates:
                - Path=/api/points/**, /api/payments/**

            - id: point-api-docs
              uri: http://localhost:8086
              predicates:
                - Path=/v3/api-docs/point
              filters:
                - RewritePath=/v3/api-docs/point, /v3/api-docs

            - id: search-api
              uri: http://localhost:8082
              predicates:
                - Path=/api/searches/**

            - id: search-api-docs
              uri: http://localhost:8082
              predicates:
                - Path=/v3/api-docs/search
              filters:
                - RewritePath=/v3/api-docs/search, /v3/api-docs

  kafka:
    bootstrap-servers: localhost:9092

member-service:
  url: http://localhost:8083
