#file: noinspection HttpUrlsUsage, SpellCheckingInspection
spring:
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

  r2dbc:
    url: ${SPRING_R2DBC_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: member-api
              uri: http://member-service:8083
              predicates:
                - Path=/api/members/**, /api/auth/**, /api/notifications/**

            - id: member-docs
              uri: http://member-service:8083
              predicates:
                - Path=/v3/api-docs/member
              filters:
                - RewritePath=/v3/api-docs/member, /v3/api-docs

            - id: commerce-api
              uri: http://commerce-service:8087
              predicates:
                - Path=/api/orders/**, /api/carts/**, /api/balances/**, /api/products/**, /api/purchases/**

            - id: commerce-docs
              uri: http://commerce-service:8087
              predicates:
                - Path=/v3/api-docs/commerce
              filters:
                - RewritePath=/v3/api-docs/commerce, /v3/api-docs

            - id: point-api
              uri: http://point-service:8086
              predicates:
                - Path=/api/points/**, /api/payments/**

            - id: point-docs
              uri: http://point-service:8086
              predicates:
                - Path=/v3/api-docs/point
              filters:
                - RewritePath=/v3/api-docs/point, /v3/api-docs

            - id: search-api
              uri: http://search-service:8082
              predicates:
                - Path=/api/searches/**

            - id: search-docs
              uri: http://search-service:8082
              predicates:
                - Path=/v3/api-docs/search
              filters:
                - RewritePath=/v3/api-docs/search, /v3/api-docs

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}

member-service:
  url: ${MEMBER_SERVICE_URL}
