#file: noinspection HttpUrlsUsage
spring:
  application:
    name: gateway

  config:
    import: optional:configserver:${SPRING_CLOUD_CONFIG_URI:http://localhost:8888}

  cloud:
    gateway:
      server:
        webflux:
          routes:
            # === 기존 API 라우트들 ===
            - id: member-api
              uri: lb://member
              predicates:
                - Path=/api/members/**
              filters:
                - JwtAuth

            - id: member-auth-api
              uri: lb://member
              predicates:
                - Path=/api/auth/**

            - id: member-internal-api
              uri: lb://member
              predicates:
                - Path=/internal/members/**

            - id: order-api
              uri: lb://order
              predicates:
                - Path=/api/orders/**, /internal/orders/**

            - id: openapi
              uri: ${GATEWAY_HOST:http://localhost:8000}
              predicates:
                - Path=/v3/api-docs/**
              filters:
                - RewritePath=/v3/api-docs/(?<segment>.*), /$\{segment}/v3/api-docs

            - id: product-api
              uri: lb://product
              predicates:
                - Path=/api/products/**, /internal/products/**
              filters:
                - JwtAuth
                - RewritePath=/api/products/(?<segment>.*), /api/products/${segment}

            - id: group-purchase-api
              uri: lb://product
              predicates:
                - Path=/api/purchases/**, /internal/purchases/**
              filters:
                - JwtAuth
                - RewritePath=/api/purchases/(?<segment>.*), /api/purchases/${segment}

            - id: point-api
              uri: lb://point
              predicates:
                - Path=/api/points/**, /internal/points/**

            - id: elastic-search-api
              uri: lb://elastic-search
              predicates:
                - Path=/api/searches/**, /internal/searches/**

            - id: point-api
              uri: lb://point
              predicates:
                - Path=/api/points/**, /api/payments/**, /internal/points/**, /internal/payments/**

            - id: notification-api
              uri: lb://notification
              predicates:
                - Path=/api/notifications/**, /internal/notifications/**

          discovery:
            locator:
              enabled: true
              lower-case-service-id: true

springdoc:
  swagger-ui:
    # Gateway Swagger UI에서 선택할 수 있는 문서 목록
    urls:
      - name: member-service
        url: /v3/api-docs/member
      - name: order-service
        url: /v3/api-docs/order
      - name: search-service
        url: /v3/api-docs/elastic-search
      - name: notification-service
        url: /v3/api-docs/notification
      - name: point-service
        url: /v3/api-docs/point
      - name: product-service
        url: /v3/api-docs/product

    # 필요하면 경로도 커스터마이징 가능 (옵션)
    # path: /swagger-ui.html

server:
  port: 8000
