#file: noinspection HttpUrlsUsage, SpringBootApplicationYaml, SpellCheckingInspection
spring:
  application:
    name: gateway

  config:
    import: optional:configserver:${SPRING_CLOUD_CONFIG_URI:http://localhost:8888}

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: member-api
              uri: lb://member
              predicates:
                - Path=/api/members/**
              filters:
                - JwtAuth

            - id: member-internal-api
              uri: lb://member
              predicates:
                - Path=/internal/members/**
              filters:
                - InternalAuth

            - id: member-auth-api
              uri: lb://member
              predicates:
                - Path=/api/auth/**

            - id: notification-api
              uri: lb://notification
              predicates:
                - Path=/api/notifications/**
              filters:
                - JwtAuth

            - id: notification-internal-api
              uri: lb://notification
              predicates:
                - Path=/internal/notifications/**
              filters:
                - InternalAuth

            - id: order-api
              uri: lb://order
              predicates:
                - Path=/api/orders/**, /api/carts/**, /api/balances/**
              filters:
                - JwtAuth

            - id: order-internal-api
              uri: lb://order
              predicates:
                - Path=/internal/orders/**, /internal/carts/**, /internal/balances/**
              filters:
                - InternalAuth

            - id: product-api
              uri: lb://product
              predicates:
                - Path=/api/products/**, /api/purchases/**
              filters:
                - JwtAuth

            - id: product-internal-api
              uri: lb://product
              predicates:
                - Path=/internal/products/**, /internal/purchases/**
              filters:
                - InternalAuth

            - id: point-api
              uri: lb://point
              predicates:
                - Path=/api/points/**, /api/payments/**
              filters:
                - JwtAuth

            - id: point-internal-api
              uri: lb://point
              predicates:
                - Path=/internal/points/**, /internal/payments/**
              filters:
                - InternalAuth

            - id: elastic-search-api
              uri: lb://elastic-search
              predicates:
                - Path=/api/searches/**
              filters:
                - JwtAuth

            - id: elastic-search-internal-api
              uri: lb://elastic-search
              predicates:
                - Path=/internal/searches/**
              filters:
                - InternalAuth

            - id: openapi
              uri: ${GATEWAY_HOST:http://localhost:8000}
              predicates:
                - Path=/v3/api-docs/**
              filters:
                - RewritePath=/v3/api-docs/(?<segment>.*), /$\{segment}/v3/api-docs

          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}

springdoc:
  swagger-ui:
    # Gateway Swagger UI에서 선택할 수 있는 문서 목록
    urls:
      - name: member-service
        url: /v3/api-docs/member
      - name: order-service
        url: /v3/api-docs/order
      - name: search-service
        url: /v3/api-docs/elastic-search
      - name: notification-service
        url: /v3/api-docs/notification
      - name: point-service
        url: /v3/api-docs/point
      - name: product-service
        url: /v3/api-docs/product

    # 필요하면 경로도 커스터마이징 가능 (옵션)
    # path: /swagger-ui.html

server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://admin:admin@${eureka.instance.hostname:localhost}:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
    health-check-url-path: /actuator/health


management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

  tracing:
    sampling:
      probability: 1.0
    propagation:
      type: w3c  # 또는 b3

gateway:
  host: ${GATEWAY_HOST:http://localhost:8000}

token:
  internal:
    secret: ${TOKEN_INTERNAL_SECRET:"abcd"}

jwt:
  secret: ${JWT_SECRET}
  access-token-validity-period: ${JWT_ACCESS_TOKEN_VALIDITY_PERIOD}
  refresh-token-validity-period: ${JWT_REFRESH_TOKEN_VALIDITY_PERIOD}
