#file: noinspection HttpUrlsUsage, SpellCheckingInspection
spring:
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

  r2dbc:
    url: ${SPRING_R2DBC_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}

frontend:
  url: https://0982.vercel.app

member-service:
  url: ${MEMBER_SERVICE_URL}
