spring:
  application:
    name: gateway

  config:
    import: optional:configserver:http://localhost:8888

  cloud:
    gateway:
      server:
        webflux:
          routes:
            # === 기존 API 라우트들 ===
            - id: member-api
              uri: lb://member
              predicates:
                - Path=/api/members/**
              filters:
                - JwtAuth
                - RewritePath=/api/members/(?<segment>.*), /api/members/${segment}
            - id: member-auth-api
              uri: lb://member
              predicates:
                - Path=/api/auth/**
              filters:
                - RewritePath=/api/auth/(?<segment>.*), /api/auth/${segment}

            - id: member-internal-api
              uri: lb://member
              predicates:
                - Path=/internal/members/**
              filters:
#                - InternalToken
                - RewritePath=/internal/members/(?<segment>.*), /internal/members/${segment}

            - id: order-api
              uri: lb://order
              predicates:
                - Path=/api/orders/**
              filters:
                - RewritePath=/api/orders/(?<segment>.*), /api/orders/${segment}

            - id: openapi
              uri: http://${GATEWAY_HOSTNAME:localhost}:${server.port}
              predicates:
                - Path=/v3/api-docs/**
              filters:
                - RewritePath=/v3/api-docs/(?<segment>.*), /$\{segment}/v3/api-docs

            - id: product-api
              uri: lb://product
              predicates:
                - Path=/api/products/**
              filters:
                - JwtAuth
                - RewritePath=/api/products/(?<segment>.*), /api/products/${segment}

            - id: group-purchase-api
              uri: lb://product
              predicates:
                - Path=/api/purchases/**
              filters:
                - JwtAuth
                - RewritePath=/api/purchases/(?<segment>.*), /api/purchases/${segment}

            - id: point-api
              uri: lb://point
              predicates:
                - Path=/api/points/**
              filters:
                - RewritePath=/api/points/(?<segment>.*), /api/points/${segment}

            - id: elastic-search-api
              uri: lb://elastic-search
              predicates:
                - Path=/api/searches/**
              filters:
                - RewritePath=/api/searches/(?<segment>.*), /api/searches/${segment}

            - id: point-api
              uri: lb://point
              predicates:
                - Path=/api/points/**, /api/payments/**, /internal/points/**, /internal/payments/**

            - id: notification-api
              uri: lb://notification
              predicates:
                - Path=/api/notifications/**

          discovery:
            locator:
              enabled: true
              lower-case-service-id: true

springdoc:
  swagger-ui:
    # Gateway Swagger UI에서 선택할 수 있는 문서 목록
    urls:
      - name: member-service
        url: /v3/api-docs/member
      - name: order-service
        url: /v3/api-docs/order
      - name: elastic-search-service
        url: /v3/api-docs/elastic-search
    # 필요하면 경로도 커스터마이징 가능 (옵션)
    # path: /swagger-ui.html

server:
  port: 8000
