#file: noinspection HttpUrlsUsage, SpringBootApplicationYaml, SpellCheckingInspection
spring:
  application:
    name: gateway
  data:
    redis:
      host: ${GATEWAY_REDIS_HOST:localhost}   # 실제 Redis 호스트
      port: ${GATEWAY_REDIS_PORT:6379}
      database: ${GATEWAY_REDIS_DATABASE:0}
  r2dbc:
    url: ${SPRING_R2DBC_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}



  config:
    import: optional:configserver:${SPRING_CLOUD_CONFIG_URI:http://localhost:8888}

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: member-api
              uri: lb://member
              predicates:
                - Path=/api/members/**, /api/auth/**, /api/notifications/**

            - id: commerce-api
              uri: lb://commerce
              predicates:
                - Path=/api/orders/**, /api/carts/**, /api/balances/**, /api/products/**, /api/purchases/**

            - id: point-api
              uri: lb://point
              predicates:
                - Path=/api/points/**, /api/payments/**

            - id: elastic-search-api
              uri: lb://elastic-search
              predicates:
                - Path=/api/searches/**

            - id: openapi
              uri: ${GATEWAY_HOST:http://localhost:8000}
              predicates:
                - Path=/v3/api-docs/**
              filters:
                - RewritePath=/v3/api-docs/(?<segment>.*), /$\{segment}/v3/api-docs

          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}

springdoc:
  swagger-ui:
    # Gateway Swagger UI에서 선택할 수 있는 문서 목록
    urls:
      - name: member-service
        url: /v3/api-docs/member
      - name: commerce-service
        url: /v3/api-docs/commerce
      - name: search-service
        url: /v3/api-docs/elastic-search
      - name: point-service
        url: /v3/api-docs/point

    # 필요하면 경로도 커스터마이징 가능 (옵션)
    # path: /swagger-ui.html

server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://admin:admin@${eureka.instance.hostname:localhost}:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
    health-check-url-path: /actuator/health

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

  tracing:
    sampling:
      probability: 1.0
    propagation:
      type: w3c  # 또는 b3

gateway:
  host: ${GATEWAY_HOST:http://localhost:8000}

token:
  internal:
    secret: ${TOKEN_INTERNAL_SECRET:"abcd"}

jwt:
  secret: ${JWT_SECRET}
  access-token-validity-period: ${JWT_ACCESS_TOKEN_VALIDITY_PERIOD}
  refresh-token-validity-period: ${JWT_REFRESH_TOKEN_VALIDITY_PERIOD}

frontend:
  url: https://0982.vercel.app
