#file: noinspection SpellCheckingInspection
spring:
  application:
    name: ai

  datasource:
    url: ${PRODUCT_DATABASE_URL}
    driver-class-name: org.postgresql.Driver
    username: ${PRODUCT_DATABASE_USERNAME}
    password: ${PRODUCT_DATABASE_PASSWORD}

  flyway:
    enabled: true
    default-schema: ai_schema
    schemas:
      - ai_schema
    create-schemas: true

  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      embedding:
        options:
          model: ${OPENAI_EMBEDDING_MODEL:text-embedding-3-small}


server:
  port: 8088

client:
  search: ${CLIENT_SEARCH_URL:http://search-service:8082}
