#file: noinspection HttpUrlsUsage, SpellCheckingInspection
spring:
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}

token:
  internal:
    secret: ${TOKEN_INTERNAL_SECRET}

client:
  commerce: ${CLIENT_COMMERCE}
