#file: noinspection HttpUrlsUsage, SpellCheckingInspection
spring:
  elasticsearch:
    uris: ${SPRING_ELASTICSEARCH_URIS}
    connection-timeout: 1s
    socket-timeout: 3s
    #    추후 xpack.security.enabled=false 변경 시
    #    username: elastic
    #    password: your_password

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}

token:
  internal:
    secret: ${TOKEN_INTERNAL_SECRET}
