#file: noinspection SpellCheckingInspection
name: Update Certification
on:
  push:
    branches:
      - dev
      - feature/ci-cd-*test
    paths:
      - 'docs/k8s/cert/tls.yml'
      - '.github/workflows/certification-update.yml'

jobs:
  apply-certfication:
    runs-on: ubuntu-latest
    outputs:
      infra-changed: ${{ steps.check-gateway.outputs.changed }}
    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: TLS 파일 변경 확인
        id: check-tls
        run: |
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q 'docs/k8s/cert/tls\.yml'; then
            echo "changed=true" >> $GITHUB_OUTPUT
            echo "TLS file changed"
          else
            echo "changed=false" >> $GITHUB_OUTPUT
            echo "No TLS file changes"
          fi

      - name: Kubectl 설치
        uses: azure/setup-kubectl@v3

      - name: Kubeconfig 설정
        shell: bash
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBE_CONFIG }}" > $HOME/.kube/config
          chmod 600 $HOME/.kube/config

      - name: 변경된 TLS 파일 배포
        if: steps.check-tls.outputs.changed == 'true'
        shell: bash
        run: |
          set -e
          
          echo "Applying TLS..."
            kubectl apply -f ./docs/k8s/cert/tls.yml

            echo "TLS successfully applied"
