#file: noinspection SpellCheckingInspection
name: Update Certification
on:
  push:
    branches:
      - dev
      - feature/ci-cd-*test
    paths:
      - 'docs/k8s/cert/tls.yml'
      - '.github/workflows/certification-update.yml'

jobs:
  apply-certfication:
    runs-on: ubuntu-latest
    outputs:
      infra-changed: ${{ steps.check-gateway.outputs.changed }}
    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: TLS 파일 변경 확인
        id: check-tls
        run: |
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q 'docs/k8s/cert/tls\.yml'; then
            echo "changed=true" >> $GITHUB_OUTPUT
            echo "TLS file changed"
          else
            echo "changed=false" >> $GITHUB_OUTPUT
            echo "No TLS file changes"
          fi

      - name: 설정 파일을 전달 받을 폴더 생성
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.BASTION_HOST }}
          username: ${{ secrets.BASTION_USER }}
          key: ${{ secrets.BASTION_SSH_KEY }}
          port: 22
          script: |
            sudo rm -rf /tmp/k8s-cert
            mkdir -p /tmp/k8s-cert

      - name: 변경된 설정 파일을 EC2 인스턴스로 복사
        if: steps.check-tls.outputs.changed == 'true'
        uses: appleboy/scp-action@v1.0.0
        with:
          host: ${{ secrets.BASTION_HOST }}
          username: ${{ secrets.BASTION_USER }}
          key: ${{ secrets.BASTION_SSH_KEY }}
          port: 22
          source: "docs/k8s/cert/tls.yml"
          target: "/tmp/k8s-cert"
          strip_components: 3
          overwrite: true

      - name: 인스턴스 접속 후 TLS 파일 적용
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.BASTION_HOST }}
          username: ${{ secrets.BASTION_USER }}
          key: ${{ secrets.BASTION_SSH_KEY }}
          port: 22
          script: |
            echo "Applying TLS..."
            kubectl apply -f /tmp/k8s-cert/tls.yml \
              --kubeconfig=/etc/rancher/k3s/k3s.yaml

            echo "TLS successfully applied"
