name: Config Server Deploy
on:
  push:
    branches:
      - feature/ci-cd
    # 나중에 경로 추가
  workflow_run:
    workflows:
      - "Config Repo Update"
    types:
      - completed

jobs:
  deploy-config-server:
    runs-on: ubuntu-latest
    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v3

      - name: JDK 17 설정
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Gradle 빌드
        uses: gradle/gradle-build-action@v2
        with:
          arguments: clean build -x test
          build-root-directory: ./config

      - name: Docker Hub 로그인
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker 이미지 빌드 및 푸시
        uses: docker/build-push-action@v4
        with:
          context: ./config
          push: true
          tags: 0909-store/config-server:${{ github.sha }}

      - name: SSH로 EC2 접속 및 배포
        # noinspection SpellCheckingInspection
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo kubectl set image deployment/config-server \
              config-server=0909-store/config-server:${{ github.sha }}
            sudo kubectl rollout status deployment/config-server
