#file: noinspection SpellCheckingInspection
name: member-deploy.yml
on:
  push:
    branches:
      - main
      - feature/ci-cd-*-test
    paths:
      - 'member/build.gradle'
      - 'member/src/**'
      - '.github/workflows/member-deploy.yml'
      - 'docs/k8s/service/member.yml'
      - 'common/src/**'
      - 'common/build.gradle'
      - 'build.gradle'

jobs:
  apply-member:
    runs-on: ubuntu-latest
    outputs:
      infra-changed: ${{ steps.check-member.outputs.changed }}
    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: member 파일 변경 확인
        id: check-member
        run: |
          if git diff --name-only HEAD^ HEAD | grep -q 'docs/k8s/service/member\.yml'; then
            echo "changed=true" >> $GITHUB_OUTPUT
            echo "member file changed"
          else
            echo "changed=false" >> $GITHUB_OUTPUT
            echo "No member file changes"
          fi

      - name: member 설정 파일을 Bastion으로 복사
        if: steps.check-member.outputs.changed == 'true'
        uses: appleboy/scp-action@v1.0.0
        with:
          host: ${{ secrets.BASTION_HOST }}
          username: ${{ secrets.BASTION_USER }}
          key: ${{ secrets.BASTION_SSH_KEY }}
          port: 22
          source: "docs/k8s/service/member.yml"
          target: "/tmp/k8s-service"
          strip_components: 3
          overwrite: true

      - name: member 리소스 적용
        if: steps.check-member.outputs.changed == 'true'
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.BASTION_HOST }}
          username: ${{ secrets.BASTION_USER }}
          key: ${{ secrets.BASTION_SSH_KEY }}
          port: 22
          command_timeout: '3m'
          script: |
            export KUBECONFIG=/etc/rancher/k3s/k3s.yaml

            echo "Applying config.yml..."
            kubectl apply -f /tmp/k8s-service/member.yml
            echo "member service applied successfully"

  deploy-member:
    needs: apply-member
    runs-on: ubuntu-latest
    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v4

      - name: JDK 17 설정
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Gradle 실행 권한 부여
        run: chmod +x ./gradlew

      - name: Docker Hub 로그인
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Jib로 Docker 이미지 빌드
        run: |
          ./gradlew :member:jib \
          -Djib.to.image=minbros/member \
          -Djib.to.tags=latest \
          -Djib.to.auth.username=${{ secrets.DOCKER_USERNAME }} \
          -Djib.to.auth.password=${{ secrets.DOCKER_PASSWORD }}

      - name: 컨트롤 플레인 접속 후 배포 명령 실행 및 이미지 정리
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.BASTION_HOST }}
          username: ${{ secrets.BASTION_USER }}
          key: ${{ secrets.BASTION_SSH_KEY }}
          port: 22
          script: |
            echo "Updating deployment..."
            kubectl set image deployment/member \
              member=minbros/member:latest \
              --kubeconfig=/etc/rancher/k3s/k3s.yaml

            echo "Waiting for rollout..."
            kubectl rollout status deployment/member \
              --timeout=2m \
              --kubeconfig=/etc/rancher/k3s/k3s.yaml

            echo "member Server deployed"
